name : CICD main
on: 
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  reusable_workflow:
    uses: DevOpsProjectsOrganization/roboshop-github-actions/.github/workflows/ci-main.yml@main
    with :
      app_type : java
      app_name : shipping
      app_env : dev
      enabled : true